services:
  postgres:
    image: postgres:16
    container_name: wedding_cms_pgsql
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: wedding
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - wedding_cms_net

volumes:
  pgdata:

networks:
  wedding_cms_net: